variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
    - release-staging/rocm-rel-7.*
  paths:
    include:
    - projects/hipblaslt
    exclude:
    - projects/hipblaslt/.githooks
    - projects/hipblaslt/.github
    - projects/hipblaslt/docs
    - projects/hipblaslt/CODEOWNERS
    - projects/hipblaslt/.*.y*ml
    - projects/hipblaslt/*.md

pr: none

stages:
- stage: hipblaslt
  jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/hipBLASLt.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: projects/hipblaslt
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
- template: templates/report-summary-check-wrapper.yml
