variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
    - release-staging/rocm-rel-7.*
  paths:
    include:
    - projects/rocsparse
    exclude:
    - projects/rocsparse/.githooks
    - projects/rocsparse/.github
    - projects/rocsparse/.jenkins
    - projects/rocsparse/docs
    - projects/rocsparse/.*.y*ml
    - projects/rocsparse/*.md

pr: none

stages:
- stage: rocsparse
  jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocSPARSE.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: projects/rocsparse
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
- template: templates/report-summary-check-wrapper.yml
