variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
    - release-staging/rocm-rel-7.*
  paths:
    include:
    - projects/rocthrust
    exclude:
    - projects/rocthrust/.githooks
    - projects/rocthrust/.github
    - projects/rocthrust/.jenkins
    - projects/rocthrust/doc
    - projects/rocthrust/docs
    - projects/rocthrust/.*.y*ml
    - projects/rocthrust/*.md
    - projects/rocthrust/LICENSE
    - projects/rocthrust/NOTICES.txt

pr: none

stages:
- stage: rocthrust
  jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocThrust.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: projects/rocthrust
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
- template: templates/report-summary-check-wrapper.yml
