variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
    - release-staging/rocm-rel-7.*
  paths:
    include:
    - shared/tensile
    exclude:
    - shared/tensile/.github
    - shared/tensile/.jenkins
    - shared/tensile/docs
    - shared/tensile/tuning_docs
    - shared/tensile/*.md
    - shared/tensile/.*.y*ml

pr: none

stages:
- stage: tensile
  jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/Tensile.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: shared/tensile
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
- template: templates/report-summary-check-wrapper.yml
