variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    include:
    - projects/hip-tests
    exclude:
    - projects/hip-tests/.jenkins
    - projects/hip-tests/CODEOWNERS
    - projects/hip-tests/LICENSE.txt
    - projects/hip-tests/**/*.md

pr: none

stages:
- stage: hip_tests
  jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/hip-tests.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: projects/hip-tests
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
- template: templates/report-summary-check-wrapper.yml
