variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    include:
    - projects/rdc
    exclude:
    - projects/rdc/.github
    - projects/rdc/docs
    - projects/rdc/.*.y*ml
    - projects/rdc/*.md
    - projects/rdc/LICENSE

pr: none

stages:
- stage: rdc
  jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rdc.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: projects/rdc
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
- template: templates/report-summary-check-wrapper.yml
