variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    include:
    - projects/rocprofiler-systems
    exclude:
    - projects/rocprofiler-systems/.github
    - projects/rocprofiler-systems/docs
    - projects/rocprofiler-systems/.*.y*ml
    - projects/rocprofiler-systems/*.md
    - projects/rocprofiler-systems/LICENSE
    - projects/rocprofiler-systems/VERSION
    - projects/rocprofiler-systems/.wordlist.txt

pr: none

stages:
- stage: rocprofiler_systems
  jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocprofiler-systems.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: projects/rocprofiler-systems
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
- template: templates/report-summary-check-wrapper.yml
